root: true

env:
    node: true
    es6: true

extends:
    - "eslint:recommended"

parserOptions:
    sourceType: "scripts"

rules:
    arrow-body-style: 0
    arrow-parens: [2, "as-needed"]
    comma-dangle: 0
    class-methods-use-this: 0
    func-names: 0
    no-tabs: 0
    no-underscore-dangle: 0
    padded-blocks: 0
    prefer-rest-params: 0
    prefer-spread: 0
    space-before-function-paren: 0